[tool.black]
target-versions = ["py312", "py313"]
line-length = 120

[tool.ruff]
line-length = 120

[tool.ruff.lint]
fixable = ["ALL"]
unfixable = []
select = ["NPY201"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
